/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodj_assignment;

/**
 *
 * @author jonat
 */
public class frameCustomerGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminGUI
     */
    public frameCustomerGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainMenuBar = new javax.swing.JMenuBar();
        btnMenuAdd = new javax.swing.JMenu();
        btnMenuEdit = new javax.swing.JMenu();
        btnMenuView = new javax.swing.JMenu();
        menuLogOut = new javax.swing.JMenu();
        menuConfirmLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.CardLayout());

        mainMenuBar.setPreferredSize(new java.awt.Dimension(418, 46));

        btnMenuAdd.setText("Add Order");
        btnMenuAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMenuAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenuAdd.setPreferredSize(new java.awt.Dimension(140, 22));
        mainMenuBar.add(btnMenuAdd);

        btnMenuEdit.setText("Edit Order");
        btnMenuEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMenuEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenuEdit.setPreferredSize(new java.awt.Dimension(140, 22));
        mainMenuBar.add(btnMenuEdit);

        btnMenuView.setText("View Order");
        btnMenuView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMenuView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenuView.setPreferredSize(new java.awt.Dimension(140, 22));
        mainMenuBar.add(btnMenuView);

        menuLogOut.setText("Log Out");
        menuLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuLogOut.setPreferredSize(new java.awt.Dimension(142, 22));

        menuConfirmLogOut.setText("Confirm Log Out?");
        menuLogOut.add(menuConfirmLogOut);

        mainMenuBar.add(menuLogOut);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameCustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameCustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameCustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameCustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameCustomerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnMenuAdd;
    private javax.swing.JMenu btnMenuEdit;
    private javax.swing.JMenu btnMenuView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem menuConfirmLogOut;
    private javax.swing.JMenu menuLogOut;
    // End of variables declaration//GEN-END:variables
}
