/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oodj_assignment;

/**
 *
 * @author jonat
 */
public class frameAdminGUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminGUI
     */
    public frameAdminGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelOrderAdd2 = new oodj_assignment.panelOrderAdd();
        mainMenuBar = new javax.swing.JMenuBar();
        menuCustomer = new javax.swing.JMenu();
        menuAddCustomer = new javax.swing.JMenuItem();
        menuUpdateRemoveCustomer = new javax.swing.JMenuItem();
        menuViewCustomer = new javax.swing.JMenuItem();
        menuOrder = new javax.swing.JMenu();
        menuAddOrder = new javax.swing.JMenuItem();
        menuUpdateCancelOrder = new javax.swing.JMenuItem();
        menuViewOrder = new javax.swing.JMenuItem();
        menuProduct = new javax.swing.JMenu();
        menuAddProduct = new javax.swing.JMenuItem();
        menuUpdateRemoveProduct = new javax.swing.JMenuItem();
        menuViewProduct = new javax.swing.JMenuItem();
        menuReport = new javax.swing.JMenu();
        menuLogOut = new javax.swing.JMenu();
        menuConfirmLogOut = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new java.awt.CardLayout());

        mainMenuBar.setPreferredSize(new java.awt.Dimension(418, 46));

        menuCustomer.setText("Customer Menu");
        menuCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuCustomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuCustomer.setPreferredSize(new java.awt.Dimension(140, 22));

        menuAddCustomer.setText("Add Customer");
        menuCustomer.add(menuAddCustomer);

        menuUpdateRemoveCustomer.setText("Update / Remove Customer Details");
        menuCustomer.add(menuUpdateRemoveCustomer);

        menuViewCustomer.setText("View Customer Details");
        menuCustomer.add(menuViewCustomer);

        mainMenuBar.add(menuCustomer);

        menuOrder.setText("Order Menu");
        menuOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuOrder.setPreferredSize(new java.awt.Dimension(140, 22));

        menuAddOrder.setText("Place Order");
        menuOrder.add(menuAddOrder);

        menuUpdateCancelOrder.setText("Update / Cancel Order");
        menuOrder.add(menuUpdateCancelOrder);

        menuViewOrder.setText("View Order Details");
        menuOrder.add(menuViewOrder);

        mainMenuBar.add(menuOrder);

        menuProduct.setText("Product Menu");
        menuProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuProduct.setPreferredSize(new java.awt.Dimension(140, 22));

        menuAddProduct.setText("Add New Product");
        menuProduct.add(menuAddProduct);

        menuUpdateRemoveProduct.setText("Update / Remove Product Details");
        menuProduct.add(menuUpdateRemoveProduct);

        menuViewProduct.setText("View Product Details");
        menuProduct.add(menuViewProduct);

        mainMenuBar.add(menuProduct);

        menuReport.setText("Report Menu");
        menuReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuReport.setPreferredSize(new java.awt.Dimension(140, 22));
        mainMenuBar.add(menuReport);

        menuLogOut.setText("Log Out");
        menuLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuLogOut.setPreferredSize(new java.awt.Dimension(142, 22));

        menuConfirmLogOut.setText("Confirm Log Out?");
        menuLogOut.add(menuConfirmLogOut);

        mainMenuBar.add(menuLogOut);

        setJMenuBar(mainMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelOrderAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelOrderAdd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameAdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameAdminGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem menuAddCustomer;
    private javax.swing.JMenuItem menuAddOrder;
    private javax.swing.JMenuItem menuAddProduct;
    private javax.swing.JMenuItem menuConfirmLogOut;
    private javax.swing.JMenu menuCustomer;
    private javax.swing.JMenu menuLogOut;
    private javax.swing.JMenu menuOrder;
    private javax.swing.JMenu menuProduct;
    private javax.swing.JMenu menuReport;
    private javax.swing.JMenuItem menuUpdateCancelOrder;
    private javax.swing.JMenuItem menuUpdateRemoveCustomer;
    private javax.swing.JMenuItem menuUpdateRemoveProduct;
    private javax.swing.JMenuItem menuViewCustomer;
    private javax.swing.JMenuItem menuViewOrder;
    private javax.swing.JMenuItem menuViewProduct;
    private oodj_assignment.panelOrderAdd panelOrderAdd2;
    // End of variables declaration//GEN-END:variables
}
